### PR TITLE
Calendar app

### PR DESCRIPTION
**Pull request by jvansant**
I have finished what I think should be a good enough calendar app for now. Please review and holler at me if there is anything that needs immediate attention before this merge.

Otherwise additional fixes (later) should include:
- #84 Not sure how to use datatables with react. It is very easy to implement in a regular js file. 
- #85 Everytime a new team is created or a user is added to a team you have to log out and back in to reset the state of those lists in the calendar app. we will need to fix this dataflow and component reload issue.

Please feel free to add issues to the above list. Just remember, we already plan to discuss and settle on the exact UI in the future. Maybe brainstorm and write down your own ideas as you review.

### CODE REVIEW

**Comment by willda07** [comment]
Couple of comments:

- [ ] What is the purpose of the CalendarList folder? Does the CSS do anything?
- [ ] Definitely need to validate the data so that a date can't end before it begins. Also shouldn't allow users to pick a date in the past.
- [ ] Tables throughout the app should be consistent with styling. Currently contacts are in a table with alternating light/dark for each row. I don't care what it is but they should all be the same.
- [ ] console.log statements always need to be removed or commented out before going into staging
- [ ] parseDate function on line 185 is not used
- [ ] forceUpdate() on line 197 shouldn't be used -- if you have to use it, you're updating the state incorrectly somewhere
- [ ] Filtering the calendar by team or user doesn't seem to work, both just clear it
- [ ] Date isn't displayed correctly in the table
- [ ] Event details (and event creator?) should be displayed in the table
- [ ] 'X' / delete event column should be on the far left and much smaller
- [ ] Condense deleteUserEvent and deleteTeamEvent into one function
- [ ] I'm pretty sure there's a better way to parse the date on lines 98 and 100, but if it works for now that's fine.
- [ ] Condense the two calls of setState into one on lines 88/89

**Review by willda07 — CHANGES_REQUESTED** [review]
See my comments on the main page for changes.

**Comment by jvansant** [comment]
Thanks for the comments. Let's go over these together tomorrow before merging. I'll make a few updates on my own before then if time.

**Review by willda07 — APPROVED** [review]
Finished all of the items in the checklist. Will merge now.

**Pull request merged**
