### PR TITLE
Teams features

### PR DESCRIPTION
**Pull request by swopnilnep**
Added Team Settings Page. Currently only works for Teams without a space in their name for now. Need to refactor this once #78, #79 and https://github.com/opus-tm/mvp-backend/issues/82 is complete.

### CODE REVIEW

**Review by jvansant — COMMENTED** [review]
Looks like a good outline to start. However, when a ran it locally, it would not let me log in. Not sure what is causing that- it seems like your changes shouldn't have effected it.
image

**Comment by willda07** [comment]
> Looks like a good outline to start. However, when a ran it locally, it would not let me log in. Not sure what is causing that- it seems like your changes shouldn't have effected it.
> image

Change the host in the api service from local to remote

**Comment by swopnilnep** [comment]
@jvansant As David mentioned, that was due to the `useLocal` in `api.service` being set to true. It should work locally without any changes now.

**Review by willda07 — APPROVED** [review]
Looks good -- I assume there will be more to come in terms of invitations, leave/join, and so on.

**Comment by swopnilnep** [comment]
Yes, currently working on a few dependencies in order to do that. Features including invitations, add/remove member, invite, set permissions etc are in the works for this page.

**Pull request merged**
