### PR TITLE
Announcements page

### LINKED ISSUE #59: Announcements Page
* Members of a group should be able to create announcements
* These announcements are visible to everyone in their group

### PR DESCRIPTION
**Pull request by willda07**
Adds the announcements feature to the app.
* Users can create new announcements with priority high/medium/low
* Users can view announcements for their teams
* Each announcement contains info about the creator, priority, body text, associated team, and associated event

Closes  #59, #41, #63, #67, #68, #70

### CODE REVIEW

**Comment by jvansant** [comment]
It would be nice to have #66.
Also, I will begin #67 on this branch instead of the schedule/calendar right now.

**Review by jvansant — CHANGES_REQUESTED** [review]
# Fix 
- [x] Took some time to think about this one now. 
- [x] #67 I will begin on this branch instead of the schedule/calendar right now. 
- [x] #70 We should fix this id vs event info in the table pronto.
# Non-Urgent
- [ ] #68 I think that we could simplify the announcement table.
- [ ] #63 should be quicker since the API endpoint is already there. 
- [ ] #66 should go quick.
- [ ] #69 is the one you already planned on doing. 
- [ ] #74 goes along with [#71](https://github.com/opus-tm/mvp-backend/issues/71). Will help to avoid announcement congestion down the road.

**Comment by willda07** [comment]
Looked through your requested changes Josh -- I unlinked several issues because they'll be in different pull requests down the road. The boxes that aren't checked all have explanations for why on each issue. I have yet to do #74, but will be including that in this PR.

**Review by swopnilnep — APPROVED** [review]

**Review by jvansant — APPROVED** [review]
Looks good. Let's discuss the functionality and design plans for this page further.

**Pull request merged**
